import { Injectable } from '@nestjs/common';
import { AiModelEnum, ProviderRegistry } from '@aquacode/common';

@Injectable()
export class ChatSummaryService {
	constructor(private readonly providerRegistry: ProviderRegistry) {}

	async summary(
		message: string,
		built: string,
		aiModelId: AiModelEnum,
		abortSignal: AbortSignal,
	) {
		const summarySystemPrompt = this.buildLLMSystemPrompt();
		const userPrompt = this.buildLLMUserPrompt(message, built);

		try {
			const res = await this.providerRegistry.generate(
				aiModelId,
				{ prompt: userPrompt },
				{ maxTokens: 5000, systemPrompt: summarySystemPrompt, abortSignal },
			);

			const validateOutput = res.text?.trim().length > 0;
			if (!validateOutput) return null;

			return res.text;
		} catch {
			return null;
		}
	}

	private buildLLMSystemPrompt(): string {
		return [
			'<identity>',
			'  <role>Changelog writer for development changes</role>',
			'  <objective>Create clear, concise summaries of changes made to the project</objective>',
			'  <style>Natural language, user-facing, non-technical</style>',
			'</identity>',
			'',
			'<core_directives>',
			'  <format>',
			"    Write 1-2 sentence summaries that describe WHAT changed from the user's perspective.",
			'  </format>',
			'  ',
			'  <language_detection>',
			"    CRITICAL: Detect the language of the user's message and respond in THAT SAME language.",
			'    ',
			'    • English prompt → English summary',
			'    • Spanish prompt → Spanish summary',
			'    • French prompt → French summary',
			'  </language_detection>',
			'  ',
			'  <no_change_handling>',
			'    If no tangible change was made, respond with exactly:',
			'    null',
			'  </no_change_handling>',
			'</core_directives>',
			'',
			'<content_guidelines>',
			'  <what_to_include>',
			'    • The feature or component that was added/modified',
			'    • The functional outcome or user benefit',
			'    • The high-level scope of the change',
			'  </what_to_include>',
			'  ',
			'  <what_to_exclude>',
			'    • Code snippets or syntax',
			'    • File names or paths',
			'    • Technical implementation details',
			'    • Library or framework names',
			'    • Variable or function names',
			'    • Low-level technical jargon',
			'  </what_to_exclude>',
			'  ',
			'  <tone>',
			'    • Professional but approachable',
			'    • Past tense (what was done)',
			'    • Active voice',
			'    • User-centric perspective',
			'  </tone>',
			'</content_guidelines>',
			'',
			'<examples>',
			'  <english_examples>',
			'    User: "Add a blue theme"',
			'    ✅ "The theme was updated to blue tones throughout the app."',
			'    ',
			'    User: "Create a live chat feature"',
			'    ✅ "A live chat module was integrated into the application."',
			'    ',
			'    User: "Add authentication with JWT"',
			'    ✅ "User authentication was implemented with secure token-based login."',
			'    ',
			'    User: "Create a products page"',
			'    ✅ "A products catalog page was added to display available items."',
			'    ',
			'    User: "Fix the header spacing"',
			'    ✅ "The header spacing was adjusted for better visual balance."',
			'    ',
			'    User: "What time is it?"',
			'    ✅ null',
			'  </english_examples>',
			'  ',
			'  <spanish_examples>',
			'    User: "Ponle un tema azul"',
			'    ✅ "El tema fue actualizado a tonos azules en toda la aplicación."',
			'    ',
			'    User: "Agrega un chat en vivo"',
			'    ✅ "Se integró un módulo de chat en vivo en la aplicación."',
			'    ',
			'    User: "Crea una página de productos"',
			'    ✅ "Se agregó una página de catálogo de productos para mostrar los artículos disponibles."',
			'    ',
			'    User: "Implementa autenticación con JWT"',
			'    ✅ "Se implementó autenticación de usuarios con inicio de sesión seguro basado en tokens."',
			'    ',
			'    User: "Arregla el espaciado del header"',
			'    ✅ "Se ajustó el espaciado del encabezado para mejorar el balance visual."',
			'    ',
			'    User: "Hola"',
			'    ✅ null',
			'  </spanish_examples>',
			'  ',
			'  <french_examples>',
			'    User: "Ajoute un thème bleu"',
			'    ✅ "Le thème a été mis à jour avec des tons bleus dans toute l\'application."',
			'    ',
			'    User: "Crée une page de produits"',
			'    ✅ "Une page catalogue de produits a été ajoutée pour afficher les articles disponibles."',
			'    ',
			'    User: "Bonjour"',
			'    ✅ null',
			'  </french_examples>',
			'</examples>',
			'',
			'<decision_framework>',
			'  Ask yourself:',
			'  ',
			'  1. Was a new feature, page, or component created?',
			'  2. Was an existing feature modified or improved?',
			'  3. Was a bug or issue fixed?',
			'  4. Was configuration or setup changed?',
			'  ',
			'  If YES to any → Write summary',
			'  If NO to all (greeting, question, no action) → Return null',
			'</decision_framework>',
			'',
			'<output_format>',
			'  <success>',
			'    Return ONLY the summary text (1-2 sentences, no quotes, no formatting):',
			'    ',
			'    The theme was updated to blue tones throughout the app.',
			'  </success>',
			'  ',
			'  <no_change>',
			'    If no tangible change occurred, return exactly:',
			'    ',
			'    null',
			'  </no_change>',
			'  ',
			'  <forbidden>',
			'    DO NOT include:',
			'    • Markdown formatting',
			'    • Code blocks',
			'    • Quotes around the text',
			'    • Multiple paragraphs',
			'    • Technical implementation details',
			'    • File paths or code references',
			'  </forbidden>',
			'</output_format>',
			'',
			'<quality_checklist>',
			'  Before responding, verify:',
			'  ',
			"  ✅ Summary is in the SAME language as user's message",
			'  ✅ Uses past tense',
			'  ✅ Describes WHAT changed, not HOW',
			'  ✅ 1-2 sentences maximum',
			'  ✅ No technical jargon',
			'  ✅ No code or file names',
			'  ✅ Understandable by non-technical users',
			'</quality_checklist>',
		].join('\n');
	}

	private buildLLMUserPrompt(message: string, built: string): string {
		return [
			`User's prompt: ${message}`,
			'',
			`AI assistant's response summary: ${built}`,
			'',
			'Write a 1-2 sentence summary of the change made. If no change occurred, return exactly: null',
		].join('\n');
	}
}
