export const JOBS_QUEUE_NAMES = {
	SANDBOX_JOBS: 'SANDBOX_JOBS',
	DEPLOYMENT_JOBS: 'DEPLOYMENT_JOBS',
};

export const JOBS_QUEUE_JOB_NAMES = {
	CREATE_SANDBOX: 'CREATE_SANDBOX',
	CREATE_PREVIEW_DEPLOYMENT: 'CREATE_PREVIEW_DEPLOYMENT',
};
