'use client';

import { useState, FormEvent } from 'react';
import { Button, Modal, ModalContent, Input, ModalHeader, ModalBody } from '@/components/ui';
import { ConnectionSchemaFieldInterface, ConnectionSchemaItemInterface } from '@/interfaces/connection-interface';
import { fetchClient, FetchClientError } from '@/utils/fetch-client';
import { WorkspaceModalDetailRow } from './workspace-modal-detail-row';
import { generateULID } from '@/utils/id-generator';

interface ProjectContentCreateDocumentModalProps {
  isOpen: boolean;
  onClose: () => void;
  connection: string;
  schema: ConnectionSchemaItemInterface;
  onDocumentCreated?: () => void;
}

// Field Types
const FIELD_TYPE_STRING = 'String';
const FIELD_TYPE_NUMBER = 'Number';
const FIELD_TYPE_BOOLEAN = 'Boolean';
const FIELD_TYPE_STRING_ARRAY = '[String]';
const FIELD_TYPE_DATE = 'Date';

// Special Field Names
const FIELD_NAME_CREATED_AT = 'createdAt';
const FIELD_NAME_UPDATED_AT = 'updatedAt';

// Default Values
const DEFAULT_VALUE_DATE_NOW = 'Date.now';
const DEFAULT_VALUE_STRING = '';
const DEFAULT_VALUE_NUMBER = 0;
const DEFAULT_VALUE_BOOLEAN = false;
const DEFAULT_VALUE_ARRAY: string[] = [];

// Error Messages
const ERROR_DOCUMENT_CREATE_FAILED = 'Document could not be created. Please try again.';

// UI Messages
const MESSAGE_MODAL_TITLE = 'Create new document';
const MESSAGE_ARRAY_HELPER = 'Separate values with commas';
const MESSAGE_REQUIRED_INDICATOR = '*';

// UI Labels
const LABEL_CANCEL = 'Cancel';
const LABEL_CREATE = 'Create document';
const LABEL_PLACEHOLDER_PREFIX = 'Enter ';
const LABEL_ARRAY_PLACEHOLDER = 'Comma separated values';

// Array Separator
const ARRAY_VALUE_SEPARATOR = ',';

export function ProjectContentCreateDocumentModal({
  isOpen,
  onClose,
  connection,
  schema,
  onDocumentCreated,
}: ProjectContentCreateDocumentModalProps) {
  // Form State
  const [formData, setFormData] = useState<Record<string, any>>({});
  const [isCreatingDocument, setIsCreatingDocument] = useState(false);
  const [creationError, setCreationError] = useState<string | null>(null);

  const handleModalClose = () => {
    setFormData({});
    setCreationError(null);
    onClose();
  };

  const handleFieldChange = (fieldName: string, value: any) => {
    setFormData((prev) => ({
      ...prev,
      [fieldName]: value,
    }));

    if (creationError) {
      setCreationError(null);
    }
  };

  const isAutoGeneratedField = (fieldName: string): boolean => {
    return fieldName === FIELD_NAME_CREATED_AT || fieldName === FIELD_NAME_UPDATED_AT;
  };

  const getDefaultValueForField = (field: ConnectionSchemaFieldInterface): any => {
    if (field.default === DEFAULT_VALUE_DATE_NOW) {
      return new Date().toISOString().split('T')[0];
    }

    if (field.default !== undefined) {
      return field.default;
    }

    switch (field.type) {
      case FIELD_TYPE_STRING:
        return DEFAULT_VALUE_STRING;
      case FIELD_TYPE_NUMBER:
        return DEFAULT_VALUE_NUMBER;
      case FIELD_TYPE_BOOLEAN:
        return DEFAULT_VALUE_BOOLEAN;
      case FIELD_TYPE_STRING_ARRAY:
        return DEFAULT_VALUE_ARRAY;
      case FIELD_TYPE_DATE:
        return DEFAULT_VALUE_STRING;
      default:
        return DEFAULT_VALUE_STRING;
    }
  };

  const parseArrayValue = (value: string): string[] => {
    return value
      .split(ARRAY_VALUE_SEPARATOR)
      .map((item) => item.trim())
      .filter(Boolean);
  };

  const formatArrayValue = (value: any): string => {
    return Array.isArray(value) ? value.join(`${ARRAY_VALUE_SEPARATOR} `) : DEFAULT_VALUE_STRING;
  };

  const renderStringArrayField = (field: ConnectionSchemaFieldInterface, index: number) => {
    const fieldValue = formData[field.name] ?? getDefaultValueForField(field);
    const showBorderTop = index > 0;

    return (
      <div
        key={field.name}
        className={`px-2.5 py-2 ${showBorderTop ? 'border-t border-neutral-200 dark:border-white/20' : ''}`}
      >
        <label className='mb-1.5 block text-sm font-normal text-neutral-900 dark:text-white'>
          {field.name}
          {field.required && <span className='ml-1 text-red-500'>{MESSAGE_REQUIRED_INDICATOR}</span>}
        </label>
        <Input
          type='text'
          placeholder={LABEL_ARRAY_PLACEHOLDER}
          value={formatArrayValue(fieldValue)}
          onValueChange={(value) => {
            const arrayValue = parseArrayValue(value);
            handleFieldChange(field.name, arrayValue);
          }}
          size='sm'
          classNames={{
            inputWrapper: 'border border-neutral-200 dark:border-neutral-700',
          }}
        />
        <p className='mt-1 text-xs text-neutral-500 dark:text-neutral-400'>{MESSAGE_ARRAY_HELPER}</p>
      </div>
    );
  };

  const renderBooleanField = (field: ConnectionSchemaFieldInterface, index: number) => {
    const fieldValue = formData[field.name] ?? getDefaultValueForField(field);

    return (
      <WorkspaceModalDetailRow
        key={field.name}
        label={field.name}
        value={fieldValue}
        isFirst={index === 0}
        isEditable
        type='boolean'
        required={field.required}
        onChange={(value) => handleFieldChange(field.name, value)}
      />
    );
  };

  const renderEnumField = (field: ConnectionSchemaFieldInterface, index: number) => {
    const fieldValue = formData[field.name] ?? getDefaultValueForField(field);

    return (
      <WorkspaceModalDetailRow
        key={field.name}
        label={field.name}
        value={fieldValue}
        isFirst={index === 0}
        isEditable
        type='select'
        required={field.required}
        options={field.enum}
        onChange={(value) => handleFieldChange(field.name, value)}
      />
    );
  };

  const renderNumberField = (field: ConnectionSchemaFieldInterface, index: number) => {
    const fieldValue = formData[field.name] ?? getDefaultValueForField(field);

    return (
      <WorkspaceModalDetailRow
        key={field.name}
        label={field.name}
        value={fieldValue}
        isFirst={index === 0}
        isEditable
        type='number'
        required={field.required}
        onChange={(value) => handleFieldChange(field.name, value)}
      />
    );
  };

  const renderDateField = (field: ConnectionSchemaFieldInterface, index: number) => {
    const fieldValue = formData[field.name] ?? getDefaultValueForField(field);

    return (
      <WorkspaceModalDetailRow
        key={field.name}
        label={field.name}
        value={fieldValue}
        isFirst={index === 0}
        isEditable
        type='date'
        required={field.required}
        onChange={(value) => handleFieldChange(field.name, value)}
      />
    );
  };

  const renderTextField = (field: ConnectionSchemaFieldInterface, index: number) => {
    const fieldValue = formData[field.name] ?? getDefaultValueForField(field);

    return (
      <WorkspaceModalDetailRow
        key={field.name}
        label={field.name}
        value={fieldValue}
        isFirst={index === 0}
        isEditable
        type='text'
        required={field.required}
        maxLength={field.maxlength}
        placeholder={`${LABEL_PLACEHOLDER_PREFIX}${field.name}`}
        onChange={(value) => handleFieldChange(field.name, value)}
      />
    );
  };

  const renderField = (field: ConnectionSchemaFieldInterface, index: number) => {
    // Skip auto-generated fields
    if (isAutoGeneratedField(field.name)) {
      return null;
    }

    // Array of strings
    if (field.type === FIELD_TYPE_STRING_ARRAY) {
      return renderStringArrayField(field, index);
    }

    // Boolean field
    if (field.type === FIELD_TYPE_BOOLEAN) {
      return renderBooleanField(field, index);
    }

    // Enum field
    if (field.enum && field.enum.length > 0) {
      return renderEnumField(field, index);
    }

    // Number field
    if (field.type === FIELD_TYPE_NUMBER) {
      return renderNumberField(field, index);
    }

    // Date field
    if (field.type === FIELD_TYPE_DATE) {
      return renderDateField(field, index);
    }

    // String field (default)
    return renderTextField(field, index);
  };

  const buildDocumentData = (): Record<string, any> => {
    const documentData: Record<string, any> = {};

    schema.fields.forEach((field) => {
      if (isAutoGeneratedField(field.name)) {
        return;
      }

      const hasFormValue = formData[field.name] !== undefined && formData[field.name] !== DEFAULT_VALUE_STRING;
      const hasDefaultValue = field.default !== undefined && field.default !== DEFAULT_VALUE_DATE_NOW;

      if (hasFormValue) {
        documentData[field.name] = formData[field.name];
      } else if (hasDefaultValue) {
        documentData[field.name] = field.default;
      }
    });

    return documentData;
  };

  const handleFormSubmit = async (e: FormEvent) => {
    e.preventDefault();

    try {
      setIsCreatingDocument(true);
      setCreationError(null);

      const documentData = buildDocumentData();

      await fetchClient({
        url: '/v1/documents',
        method: 'POST',
        data: {
          _id: generateULID(schema.prefix),
          __c: connection,
          __s: schema.name,
          ...documentData,
        },
      });

      setFormData({});
      onDocumentCreated?.();
      handleModalClose();
    } catch (error) {
      if (error instanceof FetchClientError && error.response?.data?.errors) {
        setCreationError(error.response.data.errors.join(', '));
      } else {
        setCreationError(ERROR_DOCUMENT_CREATE_FAILED);
      }
    } finally {
      setIsCreatingDocument(false);
    }
  };

  const editableFields = schema.fields.filter((field) => !isAutoGeneratedField(field.name));

  return (
    <Modal
      isOpen={isOpen}
      onClose={handleModalClose}
      size='md'
      scrollBehavior='inside'
      classNames={{
        base: 'bg-white dark:bg-neutral-900',
        closeButton: 'hover:bg-neutral-100 dark:hover:bg-neutral-800',
      }}
      isDismissable={false}
      isKeyboardDismissDisabled={false}
    >
      <ModalContent>
        <ModalHeader className='px-5 py-2'>
          <div className='flex w-full items-center justify-between'>
            <div className='flex-1 text-left'>
              <span className='text-base font-semibold'>{MESSAGE_MODAL_TITLE}</span>
            </div>
          </div>
        </ModalHeader>
        <ModalBody className='px-3 py-1'>
          <div className='space-y-4'>
            <form
              id='document-form'
              onSubmit={handleFormSubmit}
              className='overflow-hidden rounded-xl border border-neutral-200 bg-white dark:border-white/20 dark:bg-neutral-800'
            >
              {editableFields.map((field, index) => renderField(field, index))}

              {creationError && (
                <div className='mx-6 mt-4 rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-600 dark:border-red-900 dark:bg-red-950 dark:text-red-400'>
                  {creationError}
                </div>
              )}
            </form>

            <div className='flex justify-end gap-2 pt-4'>
              <Button
                size='xs'
                radius='md'
                variant='light'
                className='border border-neutral-200 bg-neutral-100 px-3 py-1.5 text-sm whitespace-nowrap transition-colors hover:bg-neutral-200 dark:border-neutral-600 dark:bg-neutral-700 dark:text-neutral-200 dark:hover:bg-neutral-600'
                onPress={handleModalClose}
                disabled={isCreatingDocument}
              >
                {LABEL_CANCEL}
              </Button>
              <Button
                size='xs'
                type='submit'
                form='document-form'
                radius='md'
                className='bg-blue-600 px-4 py-1 text-sm font-medium text-white transition-colors hover:bg-blue-700'
                disabled={isCreatingDocument}
              >
                {LABEL_CREATE}
              </Button>
            </div>
          </div>
        </ModalBody>
      </ModalContent>
    </Modal>
  );
}
